-- Sử dụng master để kiểm tra và xóa database nếu tồn tại
USE master;
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'DictionaryDB')
BEGIN
    ALTER DATABASE DictionaryDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE DictionaryDB;
END
GO

-- Tạo Database DictionaryDB
CREATE DATABASE DictionaryDB;
GO

-- Sử dụng Database
USE DictionaryDB;
GO

-- Tạo bảng từ vựng
CREATE TABLE Words (
    word_id INT IDENTITY(1,1) PRIMARY KEY,
    word NVARCHAR(100) UNIQUE NOT NULL,
    language NVARCHAR(10) DEFAULT 'en', -- Ngôn ngữ của từ
    created_at DATETIME DEFAULT GETDATE()
);

CREATE INDEX idx_word ON Words (word);

-- Tạo bảng phiên âm
CREATE TABLE Phonetic (
    phonetic_id INT IDENTITY(1,1) PRIMARY KEY,
    word_id INT NOT NULL,
    phonetic NVARCHAR(100) NOT NULL, -- Phiên âm của từ
    FOREIGN KEY (word_id) REFERENCES Words(word_id) ON DELETE CASCADE
);
ALTER TABLE Phonetic ADD CONSTRAINT unique_phonetic UNIQUE (word_id, phonetic);

-- Tạo bảng lưu nghĩa của từ
CREATE TABLE Meanings (
    meaning_id INT IDENTITY(1,1) PRIMARY KEY,
    word_id INT NOT NULL,
    definition NVARCHAR(1000) NOT NULL,
    FOREIGN KEY (word_id) REFERENCES Words(word_id) ON DELETE CASCADE
);
ALTER TABLE Meanings ADD CONSTRAINT unique_meaning UNIQUE (word_id, definition);

-- Tạo bảng lưu loại từ (Đổi tên cột "type" thành "word_type" để tránh lỗi)
CREATE TABLE WordTypes (
    type_id INT IDENTITY(1,1) PRIMARY KEY,
    word_id INT NOT NULL,
    word_type NVARCHAR(50) NOT NULL,
    FOREIGN KEY (word_id) REFERENCES Words(word_id) ON DELETE CASCADE
);
ALTER TABLE WordTypes ADD CONSTRAINT unique_word_type UNIQUE (word_id, word_type);

-- Tạo bảng ví dụ sử dụng từ
CREATE TABLE Examples (
    example_id INT IDENTITY(1,1) PRIMARY KEY,
    word_id INT NOT NULL,
    example NVARCHAR(1000) NOT NULL,
    FOREIGN KEY (word_id) REFERENCES Words(word_id) ON DELETE CASCADE
);
ALTER TABLE Examples ADD CONSTRAINT unique_example UNIQUE (word_id, example);

-- Tạo bảng lịch sử tìm kiếm
CREATE TABLE SearchHistory (
    search_id INT IDENTITY(1,1) PRIMARY KEY,
    user_id INT NOT NULL,
    word NVARCHAR(100) NOT NULL,
    search_time DATETIME DEFAULT GETDATE()
);

-- Tạo bảng người dùng
CREATE TABLE Users (
    user_id INT IDENTITY(1,1) PRIMARY KEY,
    username NVARCHAR(50) UNIQUE NOT NULL,
    password_hash NVARCHAR(255) NOT NULL,
    role NVARCHAR(20) CHECK (role IN ('admin', 'user')) DEFAULT 'user',
    created_at DATETIME DEFAULT GETDATE()
);

-- Tạo tài khoản admin mặc định với mật khẩu được mã hóa SHA2_256
INSERT INTO Users (username, password_hash, role) 
VALUES ('admin', CONVERT(NVARCHAR(255), HASHBYTES('SHA2_256', 'admin123')), 'admin');

-- Cấp quyền truy cập cho user
CREATE USER dictionary_user FOR LOGIN dictionary_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON Words TO dictionary_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON Phonetic TO dictionary_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON Meanings TO dictionary_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON WordTypes TO dictionary_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON Examples TO dictionary_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON SearchHistory TO dictionary_user;

-- Cho phép truy cập từ xa
EXEC sp_configure 'show advanced options', 1;
RECONFIGURE;
EXEC sp_configure 'remote access', 1;
RECONFIGURE;
GO
-- Chèn dữ liệu mẫu vào bảng Words
INSERT INTO Words (word) VALUES ('Ability'),
('Absorb'),
('Accept'),
('Achieve'),
('Active'),
('Admire'),
('Advice'),
('Afford'),
('Agree'),
('Allow'),
('Amuse'),
('Analyse'),
('Announce'),
('Answer'),
('Apologize'),
('Appear'),
('Apply'),
('Arrange'),
('Arrive'),
('Attract'),
('Balance'),
('Benefit'),
('Believe'),
('Build'),
('Bold'),
('Behavior'),
('Bravery'),
('Break'),
('Bright'),
('Brief'),
('Business'),
('Busy'),
('Bond'),
('Brave'),
('Basic'),
('Boost'),
('Budget'),
('Broadcast'),
('Breeze'),
('Brilliant'),
('Calculate'),
('Capacity'),
('Capture'),
('Careful'),
('Celebrate'),
('Challenge'),
('Characteristic'),
('Choice'),
('Civilization'),
('Clarify'),
('Climate'),
('Comfortable'),
('Community'),
('Compete'),
('Complicated'),
('Conclusion'),
('Confident'),
('Consider'),
('Construct'),
('Courage'),
('Damage'),
('Dangerous'),
('Daughter'),
('Decision'),
('Declare'),
('Decrease'),
('Defeat'),
('Defend'),
('Definition'),
('Deliberate'),
('Delicious'),
('Deliver'),
('Demand'),
('Democracy'),
('Demonstrate'),
('Deny'),
('Department'),
('Describe'),
('Destroy'),
('Develop'),
('Eager'),
('Earn'),
('Earthquake'),
('Economy'),
('Educate'),
('Efficient'),
('Effort'),
('Elderly'),
('Electricity'),
('Elegant'),
('Eliminate'),
('Embarrass'),
('Emergency'),
('Emotion'),
('Employ'),
('Encourage'),
('Endanger'),
('Energy'),
('Enormous'),
('Escape'),
('Famous'),
('Fast'),
('Fear'),
('Feature'),
('Feed'),
('Feel'),
('Festival'),
('Fight'),
('Find'),
('Finish'),
('Fire'),
('Firm'),
('Fit'),
('Fix'),
('Flat'),
('Flight'),
('Floor'),
('Fluently'),
('Follow'),
('Fresh'),
('Gain'),
('Game'),
('Garden'),
('Gather'),
('General'),
('Gently'),
('Giant'),
('Gift'),
('Give'),
('Glad'),
('Global'),
('Glove'),
('Go'),
('Goal'),
('Golden'),
('Good'),
('Government'),
('Grab'),
('Gracefully'),
('Grow'),
('Habit'),
('Happy'),
('Hard'),
('Harm'),
('Hat'),
('Hate'),
('Have'),
('Health'),
('Hear'),
('Heavy'),
('Help'),
('Here'),
('Hero'),
('High'),
('History'),
('Hit'),
('Hold'),
('Home'),
('Hope'),
('Huge'),
('Idea'),
('Ideal'),
('Identify'),
('Ignore'),
('Ill'),
('Illustrate'),
('Imagine'),
('Immediate'),
('Import'),
('Improve'),
('Include'),
('Increase'),
('Industry'),
('Influence'),
('Inform'),
('Initial'),
('Injure'),
('Inside'),
('Instead'),
('Interest'),
('Jacket'),
('Jam'),
('January'),
('Jeans'),
('Jelly'),
('Jeopardy'),
('Jet'),
('Jewelry'),
('Jigsaw'),
('Jingle'),
('Jolly'),
('Journalist'),
('Journey'),
('Judge'),
('Juicy'),
('Jump'),
('Junction'),
('Jungle'),
('Junior'),
('Justice'),
('Keep'),
('Key'),
('Kind'),
('King'),
('Kick'),
('Kiss'),
('Kitchen'),
('Knife'),
('Knowledge'),
('Knock'),
('Knee'),
('Know'),
('Known'),
('Knot'),
('Kid'),
('Kill'),
('Kangaroo'),
('Kite'),
('Kickoff'),
('Knockout'),
('Label'),
('Labor'),
('Ladder'),
('Landscape'),
('Language'),
('Large'),
('Laugh'),
('Launch'),
('Lawyer'),
('Lazy'),
('Leader'),
('Leaf'),
('Learn'),
('Lecture'),
('Legal'),
('Length'),
('Letter'),
('Library'),
('Light'),
('Lucky'),
('Machine'),
('Magazine'),
('Magic'),
('Maintain'),
('Major'),
('Manage'),
('Market'),
('Marry'),
('Material'),
('Matter'),
('Measure'),
('Medicine'),
('Member'),
('Memory'),
('Mention'),
('Message'),
('Metal'),
('Middle'),
('Modern'),
('Music'),
('Name'),
('Nation'),
('Natural'),
('Necessary'),
('Need'),
('Negative'),
('Neighbor'),
('Network'),
('Never'),
('Newspaper'),
('Nice'),
('Night'),
('Noble'),
('Normal'),
('North'),
('Notice'),
('Novel'),
('Number'),
('Nutrition'),
('Nurse'),
('Objective'),
('Obtain'),
('Obvious'),
('Occasion'),
('Occupy'),
('Occur'),
('Offer'),
('Office'),
('Official'),
('Often'),
('Old'),
('Omit'),
('Open'),
('Operate'),
('Opinion'),
('Opportunity'),
('Opposite'),
('Order'),
('Ordinary'),
('Organize'),
('Package'),
('Page'),
('Pain'),
('Paint'),
('Paper'),
('Paragraph'),
('Park'),
('Particular'),
('Party'),
('Pass'),
('Passenger'),
('Pattern'),
('Peace'),
('Perfect'),
('Perform'),
('Period'),
('Person'),
('Picture'),
('Plan'),
('Play'),
('Qualification'),
('Quality'),
('Quantity'),
('Quarter'),
('Question'),
('Queue'),
('Quick'),
('Quiet'),
('Quite'),
('Quote'),
('Quarrel'),
('Quaint'),
('Quench'),
('Quest'),
('Quicksand'),
('Quiver'),
('Quotient'),
('Quarantine'),
('Quadrant'),
('Quasar'),
('Race'),
('Rain'),
('Raise'),
('Random'),
('Range'),
('Rapid'),
('Rare'),
('React'),
('Realize'),
('Reason'),
('Receive'),
('Recent'),
('Recognize'),
('Recommend'),
('Reduce'),
('Refuse'),
('Regular'),
('Relation'),
('Relief'),
('Require'),
('Safe'),
('Satisfy'),
('Save'),
('Scale'),
('Scene'),
('Schedule'),
('Science'),
('Search'),
('Secret'),
('Section'),
('Secure'),
('Select'),
('Sense'),
('Separate'),
('Serious'),
('Service'),
('Shadow'),
('Sharp'),
('Shelter'),
('Shine'),
('Table'),
('Talent'),
('Talk'),
('Target'),
('Taste'),
('Teach'),
('Team'),
('Technology'),
('Temperature'),
('Tender'),
('Term'),
('Test'),
('Theory'),
('Thick'),
('Throw'),
('Ticket'),
('Tidy'),
('Timid'),
('Travel'),
('Treasure'),
('Ugly'),
('Ultimate'),
('Umbrella'),
('Unbelievable'),
('Uncertain'),
('Uncomfortable'),
('Unhappy'),
('Uniform'),
('Unique'),
('Unit'),
('Universal'),
('Unknown'),
('Unlike'),
('Unload'),
('Unpleasant'),
('Update'),
('Upgrade'),
('Urgent'),
('Use'),
('Utility'),
('Vacant'),
('Vacation'),
('Valley'),
('Valuable'),
('Van'),
('Vast'),
('Vegetable'),
('Vehicle'),
('Verify'),
('Victory'),
('View'),
('Village'),
('Violent'),
('Virtual'),
('Visible'),
('Visit'),
('Vocal'),
('Volunteer'),
('Vote'),
('Vowel'),
('Wait'),
('Wake'),
('Walk'),
('Wall'),
('Want'),
('Warm'),
('Wash'),
('Watch'),
('Water'),
('Wave'),
('Weak'),
('Weather'),
('Web'),
('Welcome'),
('West'),
('Wheel'),
('Whisper'),
('White'),
('Wild'),
('Window'),
('X-ray'),
('Xenophobia'),
('Xerox'),
('Xylophone'),
('Xenon'),
('X-axis'),
('Xenophile'),
('Xylography'),
('Xenogenesis'),
('Xiphoid'),
('Xenolithic'),
('Xenoplastic'),
('Xylotomy'),
('Xenotransplant'),
('Xenograft'),
('Xylose'),
('Xenocracy'),
('Xenotropic'),
('Xenogamy'),
('Xenarthra'),
('Yacht'),
('Yard'),
('Yawn'),
('Year'),
('Yellow'),
('Yes'),
('Yesterday'),
('Yet'),
('Yield'),
('Young'),
('Youth'),
('Yogurt'),
('Yolk'),
('Yell'),
('Yearly'),
('Yahoo'),
('Yummy'),
('Yoga'),
('Yonder'),
('Yuppie'),
('Zebra'),
('Zero'),
('Zinc'),
('Zone'),
('Zoo'),
('Zoom'),
('Zephyr'),
('Zenith'),
('Zodiac'),
('Zipper');




























-- Chèn dữ liệu mẫu vào bảng Phonetic
GO
INSERT INTO Phonetic (word_id, phonetic) VALUES 
(1, N'/əˈbɪləti/'),
(2, N'/əbˈzɔːrb/'),
(3, N'/əkˈsept/'),
(4, N'/əˈtʃiːv/'),
(5, N'/ˈæktɪv/'),
(6, N'/ədˈmaɪr/'),
(7, N'/ədˈvaɪs/'),
(8, N'/əˈfɔːrd/'),
(9, N'/əˈɡriː/'),
(10, N'/əˈlaʊ/'),
(11, N'/əˈmjuːz/'),
(12, N'/ˈænəlaɪz/'),
(13, N'/əˈnaʊns/'),
(14, N'/ˈænsər/'),
(15, N'/əˈpɑːlədʒaɪz/'),
(16, N'/əˈpɪr/'),
(17, N'/əˈplaɪ/'),
(18, N'/əˈreɪndʒ/'),
(19, N'/əˈraɪv/'),
(20, N'/əˈtrækt/'),
(21, N'/ˈbæl.əns/'),
(22, N'/ˈben.ɪ.fɪt/'),
(23, N'/bɪˈliːv/'),
(24, N'/bɪld/'),
(25, N'/boʊld/'),
(26, N'/bɪˈheɪ.vjər/'),
(27, N'/ˈbreɪ.vər.i/'),
(28, N'/breɪk/'),
(29, N'/braɪt/'),
(30, N'/briːf/'),
(31, N'/ˈbɪz.nɪs/'),
(32, N'/ˈbɪz.i/'),
(33, N'/bɒnd/'),
(34, N'/breɪv/'),
(35, N'/ˈbeɪ.sɪk/'),
(36, N'/buːst/'),
(37, N'/ˈbʌdʒ.ɪt/'),
(38, N'/ˈbrɔːd.kæst/'),
(39, N'/briːz/'),
(40, N'/ˈbrɪl.jənt/'),
(41, N'/ˈkælkjəleɪt/'),
(42, N'/kəˈpæsəti/'),
(43, N'/ˈkæptʃər/'),
(44, N'/ˈkeərfl/'),
(45, N'/ˈselɪbreɪt/'),
(46, N'/ˈtʃælɪndʒ/'),
(47, N'/ˌkærəktəˈrɪstɪk/'),
(48, N'/tʃɔɪs/'),
(49, N'/ˌsɪvɪlaɪˈzeɪʃn/'),
(50, N'/ˈklærɪfaɪ/'),
(51, N'/ˈklaɪmət/'),
(52, N'/ˈkʌmftəbl/'),
(53, N'/kəˈmjuːnəti/'),
(54, N'/kəmˈpiːt/'),
(55, N'/ˈkɒmplɪkeɪtɪd/'),
(56, N'/kənˈkluːʒn/'),
(57, N'/ˈkɒnfɪdənt/'),
(58, N'/kənˈsɪdər/'),
(59, N'/kənˈstrʌkt/'),
(60, N'/ˈkʌrɪdʒ/'),
(61, N'/ˈdæmɪdʒ/'),
(62, N'/ˈdeɪndʒərəs/'),
(63, N'/ˈdɔːtər/'),
(64, N'/dɪˈsɪʒn/'),
(65, N'/dɪˈkleər/'),
(66, N'/dɪˈkriːs/'),
(67, N'/dɪˈfiːt/'),
(68, N'/dɪˈfend/'),
(69, N'/ˌdefɪˈnɪʃn/'),
(70, N'/dɪˈlɪbərət/'),
(71, N'/dɪˈlɪʃəs/'),
(72, N'/dɪˈlɪvər/'),
(73, N'/dɪˈmænd/'),
(74, N'/dɪˈmɒkrəsi/'),
(75, N'/ˈdemənstreɪt/'),
(76, N'/dɪˈnaɪ/'),
(77, N'/dɪˈpɑːrtmənt/'),
(78, N'/dɪˈskraɪb/'),
(79, N'/dɪˈstrɔɪ/'),
(80, N'/dɪˈveləp/'),
(81, N'/ˈiːɡər/'),
(82, N'/ɜːrn/'),
(83, N'/ˈɜːrθkweɪk/'),
(84, N'/ɪˈkɒnəmi/'),
(85, N'/ˈedʒukeɪt/'),
(86, N'/ɪˈfɪʃnt/'),
(87, N'/ˈefərt/'),
(88, N'/ˈeldərli/'),
(89, N'/ɪˌlekˈtrɪsəti/'),
(90, N'/ˈelɪɡənt/'),
(91, N'/ɪˈlɪmɪneɪt/'),
(92, N'/ɪmˈbærəs/'),
(93, N'/ɪˈmɜːrdʒənsi/'),
(94, N'/ɪˈmoʊʃn/'),
(95, N'/ɪmˈplɔɪ/'),
(96, N'/ɪnˈkʌrɪdʒ/'),
(97, N'/ɪnˈdeɪndʒər/'),
(98, N'/ˈenərdʒi/'),
(99, N'/ɪˈnɔːrməs/'),
(100, N'/ɪˈskeɪp/'),
(101, N'/ˈfeɪməs/'),
(102, N'/fæst/'),
(103, N'/fɪr/'),
(104, N'/ˈfiːtʃər/'),
(105, N'/fiːd/'),
(106, N'/fiːl/'),
(107, N'/ˈfestɪvl/'),
(108, N'/faɪt/'),
(109, N'/faɪnd/'),
(110, N'/ˈfɪnɪʃ/'),
(111, N'/faɪr/'),
(112, N'/fɜːrm/'),
(113, N'/fɪt/'),
(114, N'/fɪks/'),
(115, N'/flæt/'),
(116, N'/flaɪt/'),
(117, N'/flɔːr/'),
(118, N'/ˈfluːəntli/'),
(119, N'/ˈfɑːloʊ/'),
(120, N'/freʃ/'),
(121, N'/ɡeɪn/'),
(122, N'/ɡeɪm/'),
(123, N'/ˈɡɑːrdn/'),
(124, N'/ˈɡæðər/'),
(125, N'/ˈdʒenrəl/'),
(126, N'/ˈdʒentli/'),
(127, N'/ˈdʒaɪənt/'),
(128, N'/ɡɪft/'),
(129, N'/ɡɪv/'),
(130, N'/ɡlæd/'),
(131, N'/ˈɡloʊbl/'),
(132, N'/ɡlʌv/'),
(133, N'/ɡoʊ/'),
(134, N'/ɡoʊl/'),
(135, N'/ˈɡoʊldən/'),
(136, N'/ɡʊd/'),
(137, N'/ˈɡʌvərnmənt/'),
(138, N'/ɡræb/'),
(139, N'/ˈɡreɪsfəli/'),
(140, N'/ɡroʊ/'),
(141, N'/ˈhæbɪt/'),
(142, N'/ˈhæpi/'),
(143, N'/hɑːrd/'),
(144, N'/hɑːrm/'),
(145, N'/hæt/'),
(146, N'/heɪt/'),
(147, N'/hæv/'),
(148, N'/helθ/'),
(149, N'/hɪr/'),
(150, N'/ˈhevi/'),
(151, N'/help/'),
(152, N'/hɪr/'),
(153, N'/ˈhɪroʊ/'),
(154, N'/haɪ/'),
(155, N'/ˈhɪstəri/'),
(156, N'/hɪt/'),
(157, N'/hoʊld/'),
(158, N'/hoʊm/'),
(159, N'/hoʊp/'),
(160, N'/hjuːdʒ/'),
(161, N'/aɪˈdɪə/'),
(162, N'/aɪˈdiːəl/'),
(163, N'/aɪˈdentɪfaɪ/'),
(164, N'/ɪɡˈnɔːr/'),
(165, N'/ɪl/'),
(166, N'/ˈɪləstreɪt/'),
(167, N'/ɪˈmædʒɪn/'),
(168, N'/ɪˈmiːdiət/'),
(169, N'/ɪmˈpɔːrt/'),
(170, N'/ɪmˈpruːv/'),
(171, N'/ɪnˈkluːd/'),
(172, N'/ɪnˈkriːs/'),
(173, N'/ˈɪndəstri/'),
(174, N'/ˈɪnfluəns/'),
(175, N'/ɪnˈfɔːrm/'),
(176, N'/ɪˈnɪʃl/'),
(177, N'/ˈɪndʒər/'),
(178, N'/ˌɪnˈsaɪd/'),
(179, N'/ɪnˈsted/'),
(180, N'/ˈɪntrəst/'),
(181, N'/ˈdʒækɪt/'),
(182, N'/dʒæm/'),
(183, N'/ˈdʒænjuːeri/'),
(184, N'/dʒiːnz/'),
(185, N'/ˈdʒeli/'),
(186, N'/ˈdʒepərdi/'),
(187, N'/dʒet/'),
(188, N'/ˈdʒuːəlri/'),
(189, N'/ˈdʒɪɡsɔː/'),
(190, N'/ˈdʒɪŋɡl/'),
(191, N'/ˈdʒɑːli/'),
(192, N'/ˈdʒɜːrnəlɪst/'),
(193, N'/ˈdʒɜːrni/'),
(194, N'/dʒʌdʒ/'),
(195, N'/ˈdʒuːsi/'),
(196, N'/dʒʌmp/'),
(197, N'/ˈdʒʌŋkʃən/'),
(198, N'/ˈdʒʌŋɡl/'),
(199, N'/ˈdʒuːniər/'),
(200, N'/ˈdʒʌstɪs/'),
(201, N'/kiːp/'),
(202, N'/kiː/'),
(203, N'/kaɪnd/'),
(204, N'/kɪŋ/'),
(205, N'/kɪk/'),
(206, N'/kɪs/'),
(207, N'/ˈkɪtʃən/'),
(208, N'/naɪf/'),
(209, N'/ˈnɑːlɪdʒ/'),
(210, N'/nɑːk/'),
(211, N'/niː/'),
(212, N'/noʊ/'),
(213, N'/noʊn/'),
(214, N'/nɑːt/'),
(215, N'/kɪd/'),
(216, N'/kɪl/'),
(217, N'/ˌkæŋɡəˈruː/'),
(218, N'/kaɪt/'),
(219, N'/ˈkɪkˌɔːf/'),
(220, N'/ˈnɑːkaʊt/'),
(221, N'/ˈleɪbl/'),
(222, N'/ˈleɪbər/'),
(223, N'/ˈlædər/'),
(224, N'/ˈlændskeɪp/'),
(225, N'/ˈlæŋɡwɪdʒ/'),
(226, N'/lɑːrdʒ/'),
(227, N'/læf/'),
(228, N'/lɔːntʃ/'),
(229, N'/ˈlɔɪər/'),
(230, N'/ˈleɪzi/'),
(231, N'/ˈliːdər/'),
(232, N'/liːf/'),
(233, N'/lɜːrn/'),
(234, N'/ˈlektʃər/'),
(235, N'/ˈliːɡl/'),
(236, N'/leŋkθ/'),
(237, N'/ˈletər/'),
(238, N'/ˈlaɪbreri/'),
(239, N'/laɪt/'),
(240, N'/ˈlʌki/'),
(241, N'/məˈʃiːn/'),
(242, N'/ˈmæɡəziːn/'),
(243, N'/ˈmædʒɪk/'),
(244, N'/meɪnˈteɪn/'),
(245, N'/ˈmeɪdʒər/'),
(246, N'/ˈmænɪdʒ/'),
(247, N'/ˈmɑːrkɪt/'),
(248, N'/ˈmæri/'),
(249, N'/məˈtɪriəl/'),
(250, N'/ˈmætər/'),
(251, N'/ˈmeʒər/'),
(252, N'/ˈmedɪsɪn/'),
(253, N'/ˈmembər/'),
(254, N'/ˈmeməri/'),
(255, N'/ˈmenʃən/'),
(256, N'/ˈmesɪdʒ/'),
(257, N'/ˈmetl/'),
(258, N'/ˈmɪdl/'),
(259, N'/ˈmɑːdərn/'),
(260, N'/ˈmjuːzɪk/'),
(261, N'/neɪm/'),
(262, N'/ˈneɪʃn/'),
(263, N'/ˈnætʃrəl/'),
(264, N'/ˈnesəsəri/'),
(265, N'/niːd/'),
(266, N'/ˈneɡətɪv/'),
(267, N'/ˈneɪbər/'),
(268, N'/ˈnetwɜːrk/'),
(269, N'/ˈnevər/'),
(270, N'/ˈnuːzpeɪpər/'),
(271, N'/naɪs/'),
(272, N'/naɪt/'),
(273, N'/ˈnoʊbl/'),
(274, N'/ˈnɔːrml/'),
(275, N'/nɔːrθ/'),
(276, N'/ˈnoʊtɪs/'),
(277, N'/ˈnɑːvl/'),
(278, N'/ˈnʌmbər/'),
(279, N'/nuˈtrɪʃn/'),
(280, N'/nɜːrs/'),
(281, N'/əbˈdʒektɪv/'),
(282, N'/əbˈteɪn/'),
(283, N'/ˈɑːbviəs/'),
(284, N'/əˈkeɪʒən/'),
(285, N'/ˈɑːkjupaɪ/'),
(286, N'/əˈkɜːr/'),
(287, N'/ˈɔːfər/'),
(288, N'/ˈɔːfɪs/'),
(289, N'/əˈfɪʃl/'),
(290, N'/ˈɔːfn/'),
(291, N'/oʊld/'),
(292, N'/oʊˈmɪt/'),
(293, N'/ˈoʊpən/'),
(294, N'/ˈɑːpəreɪt/'),
(295, N'/əˈpɪnjən/'),
(296, N'/ˌɑːpərˈtuːnəti/'),
(297, N'/ˈɑːpəzɪt/'),
(298, N'/ˈɔːrdər/'),
(299, N'/ˈɔːrdəneri/'),
(300, N'/ˈɔːrɡənaɪz/'),
(301, N'/ˈpækɪdʒ/'),
(302, N'/peɪdʒ/'),
(303, N'/peɪn/'),
(304, N'/peɪnt/'),
(305, N'/ˈpeɪpər/'),
(306, N'/ˈpærəɡræf/'),
(307, N'/pɑːrk/'),
(308, N'/pərˈtɪkjələr/'),
(309, N'/ˈpɑːrti/'),
(310, N'/pæs/'),
(311, N'/ˈpæsɪndʒər/'),
(312, N'/ˈpætərn/'),
(313, N'/piːs/'),
(314, N'/ˈpɜːrfɪkt/'),
(315, N'/pərˈfɔːrm/'),
(316, N'/ˈpɪriəd/'),
(317, N'/ˈpɜːrsn/'),
(318, N'/ˈpɪktʃər/'),
(319, N'/plæn/'),
(320, N'/pleɪ/'),
(321, N'/ˌkwɑːlɪfɪˈkeɪʃn/'),
(322, N'/ˈkwɑːləti/'),
(323, N'/ˈkwɑːntəti/'),
(324, N'/ˈkwɔːrtər/'),
(325, N'/ˈkwestʃən/'),
(326, N'/kjuː/'),
(327, N'/kwɪk/'),
(328, N'/ˈkwaɪət/'),
(329, N'/kwaɪt/'),
(330, N'/kwoʊt/'),
(331, N'/ˈkwɑːrəl/'),
(332, N'/kweɪnt/'),
(333, N'/kwentʃ/'),
(334, N'/kwest/'),
(335, N'/ˈkwɪksænd/'),
(336, N'/ˈkwɪvər/'),
(337, N'/ˈkwoʊʃnt/'),
(338, N'/ˈkwɔːrəntiːn/'),
(339, N'/ˈkwɑːdrənt/'),
(340, N'/ˈkweɪzɑːr/'),
(341, N'/reɪs/'),
(342, N'/reɪn/'),
(343, N'/reɪz/'),
(344, N'/ˈrændəm/'),
(345, N'/reɪndʒ/'),
(346, N'/ˈræpɪd/'),
(347, N'/rer/'),
(348, N'/riˈækt/'),
(349, N'/ˈriːəlaɪz/'),
(350, N'/ˈriːzn/'),
(351, N'/rɪˈsiːv/'),
(352, N'/ˈriːsnt/'),
(353, N'/ˈrekəɡnaɪz/'),
(354, N'/ˌrekəˈmend/'),
(355, N'/rɪˈduːs/'),
(356, N'/rɪˈfjuːz/'),
(357, N'/ˈreɡjələr/'),
(358, N'/rɪˈleɪʃn/'),
(359, N'/rɪˈliːf/'),
(360, N'/rɪˈkwaɪər/'),
(361, N'/seɪf/'),
(362, N'/ˈsætɪsfaɪ/'),
(363, N'/seɪv/'),
(364, N'/skeɪl/'),
(365, N'/siːn/'),
(366, N'/ˈskedʒuːl/'),
(367, N'/ˈsaɪəns/'),
(368, N'/sɜːrtʃ/'),
(369, N'/ˈsiːkrət/'),
(370, N'/ˈsekʃn/'),
(371, N'/sɪˈkjʊr/'),
(372, N'/sɪˈlekt/'),
(373, N'/sens/'),
(374, N'/ˈsepəreɪt/'),
(375, N'/ˈsɪriəs/'),
(376, N'/ˈsɜːrvɪs/'),
(377, N'/ˈʃædoʊ/'),
(378, N'/ʃɑːrp/'),
(379, N'/ˈʃeltər/'),
(380, N'/ʃaɪn/'),
(381, N'/ˈteɪbl/'),
(382, N'/ˈtælənt/'),
(383, N'/tɔːk/'),
(384, N'/ˈtɑːrɡɪt/'),
(385, N'/teɪst/'),
(386, N'/tiːtʃ/'),
(387, N'/tiːm/'),
(388, N'/tekˈnɑːlədʒi/'),
(389, N'/ˈtemprətʃʊr/'),
(390, N'/ˈtendər/'),
(391, N'/tɜːrm/'),
(392, N'/test/'),
(393, N'/ˈθɪəri/'),
(394, N'/θɪk/'),
(395, N'/θroʊ/'),
(396, N'/ˈtɪkɪt/'),
(397, N'/ˈtaɪdi/'),
(398, N'/ˈtɪmɪd/'),
(399, N'/ˈtrævl/'),
(400, N'/ˈtreʒər/'),
(401, N'/ˈʌɡli/'),
(402, N'/ˈʌltɪmət/'),
(403, N'/ʌmˈbrelə/'),
(404, N'/ˌʌnbɪˈliːvəbl/'),
(405, N'/ʌnˈsɜːrtn/'),
(406, N'/ʌnˈkʌmfərtəbl/'),
(407, N'/ʌnˈhæpi/'),
(408, N'/ˈjuːnɪfɔːrm/'),
(409, N'/juˈniːk/'),
(410, N'/ˈjuːnɪt/'),
(411, N'/ˌjuːnɪˈvɜːrsl/'),
(412, N'/ˌʌnˈnoʊn/'),
(413, N'/ʌnˈlaɪk/'),
(414, N'/ˌʌnˈloʊd/'),
(415, N'/ʌnˈpleznt/'),
(416, N'/ʌpˈdeɪt/'),
(417, N'/ʌpˈɡreɪd/'),
(418, N'/ˈɜːrdʒənt/'),
(419, N'/juːz/'),
(420, N'/juːˈtɪləti/'),
(421, N'/ˈveɪkənt/'),
(422, N'/veɪˈkeɪʃn/'),
(423, N'/ˈvæli/'),
(424, N'/ˈvæljuəbl/'),
(425, N'/væn/'),
(426, N'/væst/'),
(427, N'/ˈvedʒtəbl/'),
(428, N'/ˈviːɪkl/'),
(429, N'/ˈverɪfaɪ/'),
(430, N'/ˈvɪktəri/'),
(431, N'/vjuː/'),
(432, N'/ˈvɪlɪdʒ/'),
(433, N'/ˈvaɪələnt/'),
(434, N'/ˈvɜːrtʃuəl/'),
(435, N'/ˈvɪzəbl/'),
(436, N'/ˈvɪzɪt/'),
(437, N'/ˈvoʊkl/'),
(438, N'/ˌvɑːlənˈtɪr/'),
(439, N'/voʊt/'),
(440, N'/ˈvaʊəl/'),
(441, N'/weɪt/'),
(442, N'/weɪk/'),
(443, N'/wɔːk/'),
(444, N'/wɔːl/'),
(445, N'/wɑːnt/'),
(446, N'/wɔːrm/'),
(447, N'/wɑːʃ/'),
(448, N'/wɑːtʃ/'),
(449, N'/ˈwɔːtər/'),
(450, N'/weɪv/'),
(451, N'/wiːk/'),
(452, N'/ˈweðər/'),
(453, N'/web/'),
(454, N'/ˈwelkəm/'),
(455, N'/west/'),
(456, N'/wiːl/'),
(457, N'/ˈwɪspər/'),
(458, N'/waɪt/'),
(459, N'/waɪld/'),
(460, N'/ˈwɪndoʊ/'),
(461, N'/ˈeks.reɪ/'),
(462, N'/ˌzen.əˈfoʊ.bi.ə/'),
(463, N'/ˈzɪr.ɑːks/'),
(464, N'/ˈzaɪ.lə.foʊn/'),
(465, N'/ˈziː.nɑːn/'),
(466, N'/ˈeks ˌæksɪs/'),
(467, N'/ˈzen.ə.faɪl/'),
(468, N'/zaɪˈlɑː.ɡrə.fi/'),
(469, N'/ˌzen.oʊˈdʒen.ə.sɪs/'),
(470, N'/ˈzaɪ.fɔɪd/'),
(471, N'/ˌze.nəˈlɪθ.ɪk/'),
(472, N'/ˌze.nəˈplæs.tɪk/'),
(473, N'/zaɪˈlɒtəmi/'),
(474, N'/ˌze.nəʊˈtræns.plænt/'),
(475, N'/ˈze.nə.ɡræft/'),
(476, N'/ˈzaɪ.loʊs/'),
(477, N'/ˈzen.ə.krə.si/'),
(478, N'/ˌze.nəˈtrɒp.ɪk/'),
(479, N'/ˌze.nəˈɡæ.mi/'),
(480, N'/ˌze.nɑːr.θrə/'),
(481, N'/jɒt/'),
(482, N'/jɑːrd/'),
(483, N'/jɔːn/'),
(484, N'/jɪr/'),
(485, N'/ˈjel.oʊ/'),
(486, N'/jes/'),
(487, N'/ˈjes.tɚ.deɪ/'),
(488, N'/jet/'),
(489, N'/jiːld/'),
(490, N'/jʌŋ/'),
(491, N'/juːθ/'),
(492, N'/ˈjoʊ.ɡɚt/'),
(493, N'/joʊk/'),
(494, N'/jel/'),
(495, N'/ˈjɪr.li/'),
(496, N'/ˈjɑː.huː/'),
(497, N'/ˈjʌm.i/'),
(498, N'/ˈjoʊ.ɡə/'),
(499, N'/ˈjɒn.dər/'),
(500, N'/ˈjʌp.i/'),
(501, N'/ˈziː.brə/'),
(502, N'/ˈzɪə.roʊ/'),
(503, N'/zɪŋk/'),
(504, N'/zoʊn/'),
(505, N'/zuː/'),
(506, N'/zuːm/'),
(507, N'/ˈzɛf.ɚ/'),
(508, N'/ˈziː.nɪθ/'),
(509, N'/ˈzoʊ.di.æk/'),
(510, N'/ˈzɪp.ɚ/');







-- Chèn dữ liệu mẫu vào bảng WordTypes
INSERT INTO WordTypes (word_id, word_type) VALUES (1, 'Noun'),
(2, 'Verb'),
(3, 'Verb'),
(4, 'Verb'),
(5, 'Adjective'),
(6, 'Verb'),
(7, 'Noun'),
(8, 'Verb'),
(9, 'Verb'),
(10, 'Verb'),
(11, 'Verb'),
(12, 'Verb'),
(13, 'Verb'),
(14, 'Noun'),
(15, 'Verb'),
(16, 'Verb'),
(17, 'Verb'),
(18, 'Verb'),
(19, 'Verb'),
(20, 'Verb'),
(21, N'Noun'),
(22, N'Noun'),
(23, N'Verb'),
(24, N'Verb'),
(25, N'Adjective'),
(26, N'Noun'),
(27, N'Noun'),
(28, N'Verb'),
(29, N'Adjective'),
(30, N'Adjective'),
(31, N'Noun'),
(32, N'Adjective'),
(33, N'Noun'),
(34, N'Adjective'),
(35, N'Adjective'),
(36, N'Verb'),
(37, N'Noun'),
(38, N'Verb'),
(39, N'Noun'),
(40, N'Adjective'),
(41, N'verb'),
(42, N'noun'),
(43, N'verb'),
(44, N'adj'),
(45, N'verb'),
(46, N'noun'),
(47, N'noun'),
(48, N'noun'),
(49, N'noun'),
(50, N'verb'),
(51, N'noun'),
(52, N'adj'),
(53, N'noun'),
(54, N'verb'),
(55, N'adj'),
(56, N'noun'),
(57, N'adj'),
(58, N'verb'),
(59, N'verb'),
(60, N'noun'),
(61, N'noun/verb'),
(62, N'adj'),
(63, N'noun'),
(64, N'noun'),
(65, N'verb'),
(66, N'noun/verb'),
(67, N'noun/verb'),
(68, N'verb'),
(69, N'noun'),
(70, N'adj'),
(71, N'adj'),
(72, N'verb'),
(73, N'noun/verb'),
(74, N'noun'),
(75, N'verb'),
(76, N'verb'),
(77, N'noun'),
(78, N'verb'),
(79, N'verb'),
(80, N'verb'),
(81, N'Adjective'),
(82, N'Verb'),
(83, N'Noun'),
(84, N'Noun'),
(85, N'Verb'),
(86, N'Adjective'),
(87, N'Noun'),
(88, N'Adjective'),
(89, N'Noun'),
(90, N'Adjective'),
(91, N'Verb'),
(92, N'Verb'),
(93, N'Noun'),
(94, N'Noun'),
(95, N'Verb'),
(96, N'Verb'),
(97, N'Verb'),
(98, N'Noun'),
(99, N'Adjective'),
(100, N'Verb'),
(101, N'Adjective'),
(102, N'Adjective, Adverb'),
(103, N'Noun, Verb'),
(104, N'Noun, Verb'),
(105, N'Verb'),
(106, N'Verb'),
(107, N'Noun'),
(108, N'Noun, Verb'),
(109, N'Verb'),
(110, N'Verb'),
(111, N'Noun, Verb'),
(112, N'Adjective, Noun'),
(113, N'Adjective, Verb'),
(114, N'Verb'),
(115, N'Adjective, Noun'),
(116, N'Noun'),
(117, N'Noun'),
(118, N'Adverb'),
(119, N'Verb'),
(120, N'Adjective'),
(121, N'Verb'),
(122, N'Noun'),
(123, N'Noun'),
(124, N'Verb'),
(125, N'Adjective'),
(126, N'Adverb'),
(127, N'Adjective'),
(128, N'Noun'),
(129, N'Verb'),
(130, N'Adjective'),
(131, N'Adjective'),
(132, N'Noun'),
(133, N'Verb'),
(134, N'Noun'),
(135, N'Adjective'),
(136, N'Adjective'),
(137, N'Noun'),
(138, N'Verb'),
(139, N'Adverb'),
(140, N'Verb'),
(141, N'Noun'),
(142, N'Adjective'),
(143, N'Adjective, Adverb'),
(144, N'Noun, Verb'),
(145, N'Noun'),
(146, N'Verb'),
(147, N'Verb'),
(148, N'Noun'),
(149, N'Verb'),
(150, N'Adjective'),
(151, N'Noun, Verb'),
(152, N'Adverb'),
(153, N'Noun'),
(154, N'Adjective, Adverb'),
(155, N'Noun'),
(156, N'Verb'),
(157, N'Verb'),
(158, N'Noun'),
(159, N'Noun, Verb'),
(160, N'Adjective'),
(161, N'Noun'),
(162, N'Adjective'),
(163, N'Verb'),
(164, N'Verb'),
(165, N'Adjective'),
(166, N'Verb'),
(167, N'Verb'),
(168, N'Adjective'),
(169, N'Verb, Noun'),
(170, N'Verb'),
(171, N'Verb'),
(172, N'Verb, Noun'),
(173, N'Noun'),
(174, N'Noun, Verb'),
(175, N'Verb'),
(176, N'Adjective'),
(177, N'Verb'),
(178, N'Adverb, Preposition'),
(179, N'Adverb'),
(180, N'Noun, Verb'),
(181, N'Noun'),
(182, N'Noun'),
(183, N'Noun'),
(184, N'Noun'),
(185, N'Noun'),
(186, N'Noun'),
(187, N'Noun'),
(188, N'Noun'),
(189, N'Noun'),
(190, N'Noun, Verb'),
(191, N'Adjective'),
(192, N'Noun'),
(193, N'Noun'),
(194, N'Noun, Verb'),
(195, N'Adjective'),
(196, N'Verb'),
(197, N'Noun'),
(198, N'Noun'),
(199, N'Adjective'),
(200, N'Noun'),
(201, N'Verb'),
(202, N'Noun'),
(203, N'Adjective, Noun'),
(204, N'Noun'),
(205, N'Verb'),
(206, N'Verb, Noun'),
(207, N'Noun'),
(208, N'Noun'),
(209, N'Noun'),
(210, N'Verb'),
(211, N'Noun'),
(212, N'Verb'),
(213, N'Adjective'),
(214, N'Noun'),
(215, N'Noun'),
(216, N'Verb'),
(217, N'Noun'),
(218, N'Noun'),
(219, N'Noun'),
(220, N'Noun'),
(221, N'Noun'),
(222, N'Noun'),
(223, N'Noun'),
(224, N'Noun'),
(225, N'Noun'),
(226, N'Adjective'),
(227, N'Verb'),
(228, N'Verb'),
(229, N'Noun'),
(230, N'Adjective'),
(231, N'Noun'),
(232, N'Noun'),
(233, N'Verb'),
(234, N'Noun'),
(235, N'Adjective'),
(236, N'Noun'),
(237, N'Noun'),
(238, N'Noun'),
(239, N'Noun, Verb, Adjective'),
(240, N'Adjective'),
(241, N'Noun'),
(242, N'Noun'),
(243, N'Noun, Adjective'),
(244, N'Verb'),
(245, N'Adjective, Noun'),
(246, N'Verb'),
(247, N'Noun'),
(248, N'Verb'),
(249, N'Noun'),
(250, N'Noun, Verb'),
(251, N'Verb'),
(252, N'Noun'),
(253, N'Noun'),
(254, N'Noun'),
(255, N'Verb'),
(256, N'Noun'),
(257, N'Noun'),
(258, N'Noun, Adjective'),
(259, N'Adjective'),
(260, N'Noun'),
(261, N'Noun'),
(262, N'Noun'),
(263, N'Adjective'),
(264, N'Adjective'),
(265, N'Verb, Noun'),
(266, N'Adjective'),
(267, N'Noun'),
(268, N'Noun'),
(269, N'Adverb'),
(270, N'Noun'),
(271, N'Adjective'),
(272, N'Noun'),
(273, N'Adjective'),
(274, N'Adjective'),
(275, N'Noun'),
(276, N'Verb'),
(277, N'Noun'),
(278, N'Noun'),
(279, N'Noun'),
(280, N'Noun'),
(281, N'Noun, Adjective'),
(282, N'Verb'),
(283, N'Adjective'),
(284, N'Noun'),
(285, N'Verb'),
(286, N'Verb'),
(287, N'Verb, Noun'),
(288, N'Noun'),
(289, N'Adjective, Noun'),
(290, N'Adverb'),
(291, N'Adjective'),
(292, N'Verb'),
(293, N'Verb, Adjective'),
(294, N'Verb'),
(295, N'Noun'),
(296, N'Noun'),
(297, N'Adjective, Noun'),
(298, N'Verb, Noun'),
(299, N'Adjective'),
(300, N'Verb'),
(301, N'Noun'),
(302, N'Noun'),
(303, N'Noun'),
(304, N'Verb, Noun'),
(305, N'Noun'),
(306, N'Noun'),
(307, N'Noun, Verb'),
(308, N'Adjective'),
(309, N'Noun'),
(310, N'Verb'),
(311, N'Noun'),
(312, N'Noun'),
(313, N'Noun'),
(314, N'Adjective'),
(315, N'Verb'),
(316, N'Noun'),
(317, N'Noun'),
(318, N'Noun'),
(319, N'Noun, Verb'),
(320, N'Verb'),
(321, N'Noun'),
(322, N'Noun'),
(323, N'Noun'),
(324, N'Noun'),
(325, N'Noun, Verb'),
(326, N'Noun, Verb'),
(327, N'Adjective'),
(328, N'Adjective'),
(329, N'Adverb'),
(330, N'Verb, Noun'),
(331, N'Noun, Verb'),
(332, N'Adjective'),
(333, N'Verb'),
(334, N'Noun'),
(335, N'Noun'),
(336, N'Verb, Noun'),
(337, N'Noun'),
(338, N'Noun, Verb'),
(339, N'Noun'),
(340, N'Noun'),
(341, N'Noun, Verb'),
(342, N'Noun, Verb'),
(343, N'Verb'),
(344, N'Adjective'),
(345, N'Noun'),
(346, N'Adjective'),
(347, N'Adjective'),
(348, N'Verb'),
(349, N'Verb'),
(350, N'Noun'),
(351, N'Verb'),
(352, N'Adjective'),
(353, N'Verb'),
(354, N'Verb'),
(355, N'Verb'),
(356, N'Verb'),
(357, N'Adjective'),
(358, N'Noun'),
(359, N'Noun'),
(360, N'Verb'),
(361, N'Adjective'),
(362, N'Verb'),
(363, N'Verb'),
(364, N'Noun'),
(365, N'Noun'),
(366, N'Noun'),
(367, N'Noun'),
(368, N'Verb, Noun'),
(369, N'Noun'),
(370, N'Noun'),
(371, N'Verb, Adjective'),
(372, N'Verb'),
(373, N'Noun'),
(374, N'Verb'),
(375, N'Adjective'),
(376, N'Noun'),
(377, N'Noun'),
(378, N'Adjective'),
(379, N'Noun'),
(380, N'Verb'),
(381, N'Noun'),
(382, N'Noun'),
(383, N'Verb'),
(384, N'Noun'),
(385, N'Noun, Verb'),
(386, N'Verb'),
(387, N'Noun'),
(388, N'Noun'),
(389, N'Noun'),
(390, N'Adjective'),
(391, N'Noun'),
(392, N'Noun, Verb'),
(393, N'Noun'),
(394, N'Adjective'),
(395, N'Verb'),
(396, N'Noun'),
(397, N'Adjective, Verb'),
(398, N'Adjective'),
(399, N'Verb, Noun'),
(400, N'Noun, Verb'),
(401, N'Adjective'),
(402, N'Adjective'),
(403, N'Noun'),
(404, N'Adjective'),
(405, N'Adjective'),
(406, N'Adjective'),
(407, N'Adjective'),
(408, N'Noun'),
(409, N'Adjective'),
(410, N'Noun'),
(411, N'Adjective'),
(412, N'Adjective'),
(413, N'Preposition'),
(414, N'Verb'),
(415, N'Adjective'),
(416, N'Verb'),
(417, N'Verb'),
(418, N'Adjective'),
(419, N'Verb, Noun'),
(420, N'Noun'),
(421, N'Adjective'),
(422, N'Noun'),
(423, N'Noun'),
(424, N'Adjective'),
(425, N'Noun'),
(426, N'Adjective'),
(427, N'Noun'),
(428, N'Noun'),
(429, N'Verb'),
(430, N'Noun'),
(431, N'Noun, Verb'),
(432, N'Noun'),
(433, N'Adjective'),
(434, N'Adjective'),
(435, N'Adjective'),
(436, N'Verb'),
(437, N'Adjective'),
(438, N'Noun, Verb'),
(439, N'Verb'),
(440, N'Noun'),
(441, N'Verb'),
(442, N'Verb'),
(443, N'Verb'),
(444, N'Noun'),
(445, N'Verb'),
(446, N'Adjective'),
(447, N'Verb'),
(448, N'Verb'),
(449, N'Noun'),
(450, N'Noun'),
(451, N'Adjective'),
(452, N'Noun'),
(453, N'Noun'),
(454, N'Verb'),
(455, N'Noun'),
(456, N'Noun'),
(457, N'Verb'),
(458, N'Adjective'),
(459, N'Adjective'),
(460, N'Noun'),
(461, N'Noun'),
(462, N'Noun'),
(463, N'Verb'),
(464, N'Noun'),
(465, N'Noun'),
(466, N'Noun'),
(467, N'Noun'),
(468, N'Noun'),
(469, N'Noun'),
(470, N'Adjective'),
(471, N'Adjective'),
(472, N'Adjective'),
(473, N'Noun'),
(474, N'Noun'),
(475, N'Noun'),
(476, N'Noun'),
(477, N'Noun'),
(478, N'Adjective'),
(479, N'Noun'),
(480, N'Noun'),
(481, N'Noun'),
(482, N'Noun'),
(483, N'Verb'),
(484, N'Noun'),
(485, N'Adjective'),
(486, N'Adverb'),
(487, N'Noun, Adverb'),
(488, N'Adverb'),
(489, N'Verb'),
(490, N'Adjective'),
(491, N'Noun'),
(492, N'Noun'),
(493, N'Noun'),
(494, N'Verb'),
(495, N'Adjective'),
(496, N'Noun'),
(497, N'Adjective'),
(498, N'Noun'),
(499, N'Adverb'),
(500, N'Noun'),
(501, N'Noun'),
(502, N'Noun'),
(503, N'Noun'),
(504, N'Noun'),
(505, N'Noun'),
(506, N'Verb'),
(507, N'Noun'),
(508, N'Noun'),
(509, N'Noun'),
(510, N'Noun');










-- Chèn dữ liệu mẫu vào bảng Meanings
INSERT INTO Meanings (word_id, definition) VALUES
(1, N'Khả năng'),
(2, N'Hấp thụ'),
(3, N'Chấp nhận'),
(4, N'Đạt được'),
(5, N'Năng động'),
(6, N'Ngưỡng mộ'),
(7, N'Lời khuyên'),
(8, N'Có khả năng chi trả'),
(9, N'Đồng ý'),
(10, N'Cho phép'),
(11, N'Làm cho vui'),
(12, N'Phân tích'),
(13, N'Thông báo'),
(14, N'Câu trả lời'),
(15, N'Xin lỗi'),
(16, N'Xuất hiện'),
(17, N'Ứng tuyển, áp dụng'),
(18, N'Sắp xếp'),
(19, N'Đến nơi'),
(20, N'Thu hút'),
(21, N'Sự cân bằng'),
(22, N'Lợi ích'),
(23, N'Tin tưởng'),
(24, N'Xây dựng'),
(25, N'Dũng cảm'),
(26, N'Hành vi'),
(27, N'Sự dũng cảm'),
(28, N'Phá vỡ'),
(29, N'Sáng và thông minh'),
(30, N'Ngắn gọn'),
(31, N'Kinh doanh'),
(32, N'Bận rộn'),
(33, N'Sự kết nối'),
(34, N'Dũng cảm'),
(35, N'Cơ bản'),
(36, N'Tăng cường'),
(37, N'Ngân sách'),
(38, N'Phát sóng'),
(39, N'Làn gió nhẹ'),
(40, N'Xuất sắc, rực rỡ'),
(41, N'tính toán'),
(42, N'sức chứa, dung tích'),
(43, N'bắt giữ, chụp lại'),
(44, N'cẩn thận'),
(45, N'ăn mừng, kỷ niệm'),
(46, N'thách thức'),
(47, N'đặc điểm'),
(48, N'sự lựa chọn'),
(49, N'nền văn minh'),
(50, N'làm rõ'),
(51, N'khí hậu'),
(52, N'thoải mái'),
(53, N'cộng đồng'),
(54, N'cạnh tranh'),
(55, N'phức tạp'),
(56, N'kết luận'),
(57, N'tự tin'),
(58, N'xem xét'),
(59, N'xây dựng'),
(60, N'lòng dũng cảm'),
(61, N'tổn hại, làm hỏng'),
(62, N'nguy hiểm'),
(63, N'con gái'),
(64, N'quyết định'),
(65, N'tuyên bố, công bố'),
(66, N'giảm xuống'),
(67, N'đánh bại, thất bại'),
(68, N'bảo vệ'),
(69, N'định nghĩa'),
(70, N'cố ý, có suy nghĩ trước'),
(71, N'ngon'),
(72, N'giao hàng, chuyển phát'),
(73, N'nhu cầu, yêu cầu'),
(74, N'nền dân chủ'),
(75, N'chứng minh, biểu tình'),
(76, N'phủ nhận'),
(77, N'phòng ban, bộ phận'),
(78, N'mô tả'),
(79, N'phá hủy'),
(80, N'phát triển'),
(81, N'Háo hức, hăng hái'),
(82, N'Kiếm được'),
(83, N'Động đất'),
(84, N'Nền kinh tế'),
(85, N'Giáo dục, giảng dạy'),
(86, N'Hiệu quả'),
(87, N'Nỗ lực'),
(88, N'Cao tuổi, lớn tuổi'),
(89, N'Điện'),
(90, N'Thanh lịch, tao nhã'),
(91, N'Loại bỏ'),
(92, N'Làm xấu hổ'),
(93, N'Trường hợp khẩn cấp'),
(94, N'Cảm xúc'),
(95, N'Thuê, tuyển dụng'),
(96, N'Khuyến khích'),
(97, N'Gây nguy hiểm'),
(98, N'Năng lượng'),
(99, N'To lớn, khổng lồ'),
(100, N'Thoát khỏi'),
(101, N'Nổi tiếng'),
(102, N'Nhanh'),
(103, N'Nỗi sợ, sợ hãi'),
(104, N'Đặc điểm, có đặc điểm'),
(105, N'Cho ăn'),
(106, N'Cảm thấy'),
(107, N'Lễ hội'),
(108, N'Trận đấu, chiến đấu'),
(109, N'Tìm thấy'),
(110, N'Hoàn thành'),
(111, N'Lửa, sa thải'),
(112, N'Vững chắc, công ty'),
(113, N'Vừa vặn, phù hợp'),
(114, N'Sửa chữa'),
(115, N'Bằng phẳng, căn hộ'),
(116, N'Chuyến bay'),
(117, N'Sàn nhà'),
(118, N'Trôi chảy'),
(119, N'Theo dõi, theo sau'),
(120, N'Tươi, mới'),
(121, N'Đạt được'),
(122, N'Trò chơi'),
(123, N'Khu vườn'),
(124, N'Tụ họp, thu thập'),
(125, N'Chung, tổng quát'),
(126, N'Nhẹ nhàng'),
(127, N'Khổng lồ'),
(128, N'Món quà'),
(129, N'Cho, tặng'),
(130, N'Vui mừng'),
(131, N'Toàn cầu'),
(132, N'Găng tay'),
(133, N'Đi'),
(134, N'Mục tiêu'),
(135, N'Vàng, quý giá'),
(136, N'Tốt'),
(137, N'Chính phủ'),
(138, N'Nắm lấy'),
(139, N'Duyên dáng'),
(140, N'Phát triển, mọc'),
(141, N'Thói quen'),
(142, N'Hạnh phúc'),
(143, N'Cứng, khó khăn'),
(144, N'Tổn hại, gây hại'),
(145, N'Mũ'),
(146, N'Ghét'),
(147, N'Có, sở hữu'),
(148, N'Sức khỏe'),
(149, N'Nghe'),
(150, N'Nặng'),
(151, N'Giúp đỡ'),
(152, N'Ở đây'),
(153, N'Anh hùng'),
(154, N'Cao'),
(155, N'Lịch sử'),
(156, N'Đánh, va vào'),
(157, N'Cầm, nắm'),
(158, N'Nhà'),
(159, N'Hy vọng'),
(160, N'To lớn'),
(161, N'Ý tưởng'),
(162, N'Lý tưởng'),
(163, N'Nhận diện'),
(164, N'Phớt lờ'),
(165, N'Ốm, bệnh'),
(166, N'Minh họa'),
(167, N'Tưởng tượng'),
(168, N'Ngay lập tức'),
(169, N'Nhập khẩu, sự nhập khẩu'),
(170, N'Cải thiện'),
(171, N'Bao gồm'),
(172, N'Tăng lên, sự gia tăng'),
(173, N'Ngành công nghiệp'),
(174, N'Ảnh hưởng'),
(175, N'Thông báo'),
(176, N'Ban đầu'),
(177, N'Làm bị thương'),
(178, N'Bên trong'),
(179, N'Thay vì'),
(180, N'Sự quan tâm, làm ai quan tâm'),
(181, N'Áo khoác'),
(182, N'Mứt, tắc đường'),
(183, N'Tháng Một'),
(184, N'Quần bò'),
(185, N'Thạch'),
(186, N'Nguy hiểm'),
(187, N'Máy bay phản lực'),
(188, N'Trang sức'),
(189, N'Trò chơi ghép hình'),
(190, N'Tiếng leng keng, ngân vang'),
(191, N'Vui vẻ'),
(192, N'Nhà báo'),
(193, N'Hành trình'),
(194, N'Thẩm phán, đánh giá'),
(195, N'Mọng nước'),
(196, N'Nhảy'),
(197, N'Giao lộ'),
(198, N'Rừng rậm'),
(199, N'Cấp dưới, nhỏ hơn'),
(200, N'Sự công bằng'),
(201, N'Giữ, duy trì'),
(202, N'Chìa khóa'),
(203, N'Tốt bụng, loại'),
(204, N'Nhà vua'),
(205, N'Đá'),
(206, N'Hôn, nụ hôn'),
(207, N'Nhà bếp'),
(208, N'Con dao'),
(209, N'Kiến thức'),
(210, N'Gõ cửa'),
(211, N'Đầu gối'),
(212, N'Biết'),
(213, N'Được biết đến'),
(214, N'Nút thắt'),
(215, N'Đứa trẻ'),
(216, N'Giết'),
(217, N'Con chuột túi'),
(218, N'Con diều'),
(219, N'Sự khởi đầu'),
(220, N'Hạ đo ván'),
(221, N'Nhãn mác'),
(222, N'Lao động'),
(223, N'Cái thang'),
(224, N'Phong cảnh'),
(225, N'Ngôn ngữ'),
(226, N'Lớn'),
(227, N'Cười'),
(228, N'Phóng, khởi động'),
(229, N'Luật sư'),
(230, N'Lười biếng'),
(231, N'Nhà lãnh đạo'),
(232, N'Chiếc lá'),
(233, N'Học'),
(234, N'Bài giảng'),
(235, N'Hợp pháp'),
(236, N'Chiều dài'),
(237, N'Lá thư, chữ cái'),
(238, N'Thư viện'),
(239, N'Ánh sáng, thắp sáng, nhẹ'),
(240, N'May mắn'),
(241, N'Máy móc'),
(242, N'Tạp chí'),
(243, N'Ma thuật, kỳ diệu'),
(244, N'Duy trì'),
(245, N'Chính, chuyên ngành'),
(246, N'Quản lý'),
(247, N'Chợ, thị trường'),
(248, N'Kết hôn'),
(249, N'Vật liệu'),
(250, N'Vấn đề, quan trọng'),
(251, N'Đo lường'),
(252, N'Thuốc'),
(253, N'Thành viên'),
(254, N'Ký ức, bộ nhớ'),
(255, N'Đề cập'),
(256, N'Tin nhắn'),
(257, N'Kim loại'),
(258, N'Giữa'),
(259, N'Hiện đại'),
(260, N'Âm nhạc'),
(261, N'Tên'),
(262, N'Quốc gia'),
(263, N'Tự nhiên'),
(264, N'Cần thiết'),
(265, N'Cần, nhu cầu'),
(266, N'Tiêu cực'),
(267, N'Hàng xóm'),
(268, N'Mạng lưới'),
(269, N'Không bao giờ'),
(270, N'Báo'),
(271, N'Tốt, đẹp'),
(272, N'Đêm'),
(273, N'Cao quý'),
(274, N'Bình thường'),
(275, N'Phía Bắc'),
(276, N'Chú ý'),
(277, N'Tiểu thuyết'),
(278, N'Con số'),
(279, N'Dinh dưỡng'),
(280, N'Y tá'),
(281, N'Mục tiêu, khách quan'),
(282, N'Đạt được'),
(283, N'Rõ ràng'),
(284, N'Dịp, cơ hội'),
(285, N'Chiếm giữ'),
(286, N'Xảy ra'),
(287, N'Đề nghị, lời đề nghị'),
(288, N'Văn phòng'),
(289, N'Chính thức, quan chức'),
(290, N'Thường xuyên'),
(291, N'Già, cũ'),
(292, N'Bỏ qua'),
(293, N'Mở, rộng mở'),
(294, N'Vận hành'),
(295, N'Ý kiến'),
(296, N'Cơ hội'),
(297, N'Đối diện, trái ngược'),
(298, N'Đặt hàng, mệnh lệnh'),
(299, N'Bình thường'),
(300, N'Tổ chức'),
(301, N'Gói hàng'),
(302, N'Trang'),
(303, N'Cơn đau'),
(304, N'Sơn, vẽ'),
(305, N'Giấy'),
(306, N'Đoạn văn'),
(307, N'Công viên, đỗ xe'),
(308, N'Cụ thể'),
(309, N'Bữa tiệc'),
(310, N'Vượt qua'),
(311, N'Hành khách'),
(312, N'Mẫu, khuôn mẫu'),
(313, N'Hòa bình'),
(314, N'Hoàn hảo'),
(315, N'Biểu diễn'),
(316, N'Giai đoạn'),
(317, N'Người'),
(318, N'Bức tranh'),
(319, N'Kế hoạch, lập kế hoạch'),
(320, N'Chơi, biểu diễn'),
(321, N'Bằng cấp'),
(322, N'Chất lượng'),
(323, N'Số lượng'),
(324, N'Một phần tư'),
(325, N'Câu hỏi, hỏi'),
(326, N'Hàng chờ, xếp hàng'),
(327, N'Nhanh chóng'),
(328, N'Yên tĩnh'),
(329, N'Khá, hoàn toàn'),
(330, N'Trích dẫn'),
(331, N'Cãi nhau'),
(332, N'Cổ kính'),
(333, N'Làm dịu'),
(334, N'Hành trình tìm kiếm'),
(335, N'Cát lún'),
(336, N'Run rẩy, bao đựng tên'),
(337, N'Thương số'),
(338, N'Cách ly'),
(339, N'Góc phần tư'),
(340, N'Chuẩn tinh'),
(341, N'Cuộc đua, đua'),
(342, N'Mưa'),
(343, N'Nâng lên, nuôi dạy'),
(344, N'Ngẫu nhiên'),
(345, N'Phạm vi'),
(346, N'Nhanh chóng'),
(347, N'Hiếm có'),
(348, N'Phản ứng'),
(349, N'Nhận ra'),
(350, N'Lý do'),
(351, N'Nhận'),
(352, N'Gần đây'),
(353, N'Nhận diện'),
(354, N'Đề xuất'),
(355, N'Giảm bớt'),
(356, N'Từ chối'),
(357, N'Thường xuyên, đều đặn'),
(358, N'Mối quan hệ'),
(359, N'Sự nhẹ nhõm'),
(360, N'Yêu cầu'),
(361, N'An toàn'),
(362, N'Làm hài lòng'),
(363, N'Tiết kiệm, cứu'),
(364, N'Cái cân, quy mô'),
(365, N'Cảnh'),
(366, N'Lịch trình'),
(367, N'Khoa học'),
(368, N'Tìm kiếm'),
(369, N'Bí mật'),
(370, N'Phần'),
(371, N'Đảm bảo, an toàn'),
(372, N'Chọn'),
(373, N'Giác quan'),
(374, N'Tách rời'),
(375, N'Nghiêm trọng'),
(376, N'Dịch vụ'),
(377, N'Bóng'),
(378, N'Sắc bén'),
(379, N'Nơi trú ẩn'),
(380, N'Chiếu sáng'),
(381, N'Cái bàn'),
(382, N'Tài năng'),
(383, N'Nói chuyện'),
(384, N'Mục tiêu'),
(385, N'Hương vị, nếm'),
(386, N'Dạy'),
(387, N'Đội nhóm'),
(388, N'Công nghệ'),
(389, N'Nhiệt độ'),
(390, N'Dịu dàng'),
(391, N'Thuật ngữ'),
(392, N'Bài kiểm tra, kiểm tra'),
(393, N'Lý thuyết'),
(394, N'Dày'),
(395, N'Ném'),
(396, N'Vé'),
(397, N'Gọn gàng, dọn dẹp'),
(398, N'Rụt rè, nhút nhát'),
(399, N'Du lịch'),
(400, N'Kho báu, trân trọng'),
(401, N'Xấu xí'),
(402, N'Tối thượng, cuối cùng'),
(403, N'Cái ô'),
(404, N'Không thể tin được'),
(405, N'Không chắc chắn'),
(406, N'Không thoải mái'),
(407, N'Không vui'),
(408, N'Đồng phục'),
(409, N'Độc nhất'),
(410, N'Đơn vị'),
(411, N'Chung, phổ biến'),
(412, N'Không xác định'),
(413, N'Không giống'),
(414, N'Dỡ hàng'),
(415, N'Khó chịu'),
(416, N'Cập nhật'),
(417, N'Nâng cấp'),
(418, N'Khẩn cấp'),
(419, N'Sử dụng'),
(420, N'Tiện ích'),
(421, N'Trống, bỏ trống'),
(422, N'Kỳ nghỉ'),
(423, N'Thung lũng'),
(424, N'Có giá trị'),
(425, N'Xe tải nhỏ'),
(426, N'Rộng lớn'),
(427, N'Rau củ'),
(428, N'Phương tiện giao thông'),
(429, N'Xác minh'),
(430, N'Chiến thắng'),
(431, N'Cảnh quan, xem'),
(432, N'Làng'),
(433, N'Bạo lực'),
(434, N'Ảo'),
(435, N'Có thể nhìn thấy'),
(436, N'Thăm'),
(437, N'Thuộc về giọng nói'),
(438, N'Tình nguyện viên, tình nguyện'),
(439, N'Bầu chọn'),
(440, N'Nguyên âm'),
(441, N'Chờ đợi'),
(442, N'Thức dậy'),
(443, N'Đi bộ'),
(444, N'Bức tường'),
(445, N'Muốn'),
(446, N'Ấm áp'),
(447, N'Rửa'),
(448, N'Xem'),
(449, N'Nước'),
(450, N'Sóng'),
(451, N'Yếu'),
(452, N'Thời tiết'),
(453, N'Mạng, trang web'),
(454, N'Chào mừng'),
(455, N'Hướng Tây'),
(456, N'Bánh xe'),
(457, N'Thì thầm'),
(458, N'Màu trắng'),
(459, N'Hoang dã'),
(460, N'Cửa sổ'),
(461, N'Tia X, chụp X-quang'),
(462, N'Sự bài ngoại'),
(463, N'Sao chép (photo)'),
(464, N'Đàn phiến gỗ'),
(465, N'Khí xenon'),
(466, N'Trục X (toán học)'),
(467, N'Người yêu thích văn hóa nước ngoài'),
(468, N'Nghệ thuật khắc gỗ'),
(469, N'Sự sinh vật lai'),
(470, N'Hình kiếm'),
(471, N'Chứa đá lạ'),
(472, N'Cấy ghép từ loài khác'),
(473, N'Khoa học cắt lát gỗ'),
(474, N'Ghép mô từ loài khác'),
(475, N'Mô cấy ghép từ loài khác'),
(476, N'Đường gỗ'),
(477, N'Chính quyền ngoại bang'),
(478, N'Sinh trưởng trên vật chủ khác'),
(479, N'Thụ phấn chéo'),
(480, N'Bộ thú tê tê và lười'),
(481, N'Du thuyền'),
(482, N'Sân'),
(483, N'Ngáp'),
(484, N'Năm'),
(485, N'Màu vàng'),
(486, N'Vâng, có'),
(487, N'Hôm qua'),
(488, N'Chưa'),
(489, N'Tạo ra, sinh lợi'),
(490, N'Trẻ'),
(491, N'Tuổi trẻ'),
(492, N'Sữa chua'),
(493, N'Lòng đỏ trứng'),
(494, N'Hét lên'),
(495, N'Hằng năm'),
(496, N'Tiếng reo hò'),
(497, N'Ngon'),
(498, N'Yoga'),
(499, N'Ở đằng kia'),
(500, N'Người trẻ thành đạt'),
(501, N'Ngựa vằn'),
(502, N'Số không'),
(503, N'Kẽm'),
(504, N'Khu vực'),
(505, N'Sở thú'),
(506, N'Phóng to, phóng nhanh'),
(507, N'Gió nhẹ'),
(508, N'Cực điểm, đỉnh cao'),
(509, N'Cung hoàng đạo'),
(510, N'Khóa kéo');













-- Chèn dữ liệu mẫu vào bảng Examples
INSERT INTO Examples (word_id, example) VALUES
(1, 'She has the ability to solve complex problems.'),
(2, 'Plants absorb sunlight to produce energy.'),
(3, 'He refused to accept the gift.'),
(4, 'She worked hard to achieve success.'),
(5, 'He is an active member of the community.'),
(6, 'I admire her dedication to work.'),
(7, 'He gave me some good advice.'),
(8, 'I cannot afford to buy a new car.'),
(9, 'I agree with your opinion.'),
(10, 'My parents do not allow me to stay out late.'),
(11, 'His jokes always amuse me.'),
(12, 'Scientists analyse the data carefully.'),
(13, 'They will announce the winner tomorrow.'),
(14, 'She did not know the answer to the question.'),
(15, 'I apologize for being late.'),
(16, 'A rainbow appeared after the rain.'),
(17, 'I want to apply for this job.'),
(18, 'She arranged the books neatly.'),
(19, 'They arrived at the airport on time.'),
(20, 'The beautiful flowers attracted many bees.'),
(21, N'He maintains a perfect balance between work and leisure.'),
(22, N'The new policy offers great benefits to employees.'),
(23, N'She believes that honesty is the best policy.'),
(24, N'They plan to build a new bridge over the river.'),
(25, N'The bold explorer ventured into unknown territories.'),
(26, N'His behavior at the meeting was very professional.'),
(27, N'The soldier was honored for his bravery during the battle.'),
(28, N'Please do not break the fragile vase during the move.'),
(29, N'The bright student always asks insightful questions in every class.'),
(30, N'The teacher gave a brief introduction to the lesson before starting the detailed discussion.'),
(31, N'She runs a successful business in the city with a focus on sustainability.'),
(32, N'He is too busy to attend the meeting because he has many projects to complete.'),
(33, N'The strong bond between the teammates was evident throughout the competition.'),
(34, N'The brave firefighter rescued the child from the burning building.'),
(35, N'Understanding basic mathematics is essential for further studies in science and engineering.'),
(36, N'The government introduced measures to boost the economy during the recession.'),
(37, N'They prepared a detailed budget for the new project before asking for additional funds.'),
(38, N'The radio station will broadcast the live concert in the evening on all channels.'),
(39, N'A cool breeze swept through the open window on a hot summer day.'),
(40, N'The scientist presented a brilliant solution to the problem that impressed the entire team.'),
(41, N'She needs to calculate the total cost.'),
(42, N'The stadium has a capacity of 50,000 people.'),
(43, N'The photographer captured a beautiful sunset.'),
(44, N'Be careful when crossing the street.'),
(45, N'They celebrate their anniversary every year.'),
(46, N'Learning a new language is a big challenge.'),
(47, N'Honesty is an important characteristic of a good leader.'),
(48, N'You have to make a choice between the two options.'),
(49, N'Ancient civilizations left behind many historical sites.'),
(50, N'Can you clarify what you mean?'),
(51, N'The climate in this region is very dry.'),
(52, N'This chair is very comfortable.'),
(53, N'She is an active member of the local community.'),
(54, N'Many companies compete for market dominance.'),
(55, N'The situation is more complicated than we thought.'),
(56, N'The conclusion of the report is well-written.'),
(57, N'He is confident about his presentation.'),
(58, N'We should consider all options before deciding.'),
(59, N'They plan to construct a new bridge.'),
(60, N'She showed great courage in facing difficulties.'),
(61, N'The storm caused serious damage to the house.'),
(62, N'It is dangerous to walk alone at night.'),
(63, N'His daughter is studying abroad.'),
(64, N'Making a decision is not always easy.'),
(65, N'The government declared a state of emergency.'),
(66, N'The number of visitors has decreased significantly.'),
(67, N'The team suffered a heavy defeat in the final.'),
(68, N'Soldiers must defend their country.'),
(69, N'Can you give me the definition of this word?'),
(70, N'It was a deliberate decision to stay silent.'),
(71, N'This cake tastes delicious.'),
(72, N'The courier will deliver your package tomorrow.'),
(73, N'The demand for electric cars is increasing.'),
(74, N'Democracy allows people to vote for their leaders.'),
(75, N'He demonstrated how to use the machine.'),
(76, N'He denied stealing the money.'),
(77, N'She works in the sales department.'),
(78, N'Can you describe what happened?'),
(79, N'The fire destroyed the entire building.'),
(80, N'She wants to develop her career in technology.'),
(81, N'She was eager to start her new job.'),
(82, N'He works hard to earn a good salary.'),
(83, N'The earthquake caused severe damage to the city.'),
(84, N'The economy is growing rapidly this year.'),
(85, N'Schools aim to educate children for the future.'),
(86, N'The new system is much more efficient than the old one.'),
(87, N'He put a lot of effort into his project.'),
(88, N'The elderly couple enjoys walking in the park every morning.'),
(89, N'The power outage left the entire city without electricity.'),
(90, N'She wore an elegant dress to the party.'),
(91, N'The company plans to eliminate unnecessary expenses.'),
(92, N'His mistake in front of everyone embarrassed him.'),
(93, N'Call 911 in case of an emergency.'),
(94, N'She could not hide her emotions when she heard the news.'),
(95, N'The company employs over 500 workers.'),
(96, N'Teachers should encourage students to ask questions.'),
(97, N'Pollution can endanger marine life.'),
(98, N'Solar panels generate renewable energy.'),
(99, N'The elephant is an enormous animal.'),
(100, N'The prisoner tried to escape from jail.'),
(101, N'He is a famous actor in Hollywood.'),
(102, N'She runs fast in the competition.'),
(103, N'He has a fear of heights.'),
(104, N'This phone has a special feature.'),
(105, N'She feeds her dog every morning.'),
(106, N'I feel happy today.'),
(107, N'The music festival was amazing.'),
(108, N'They had a fight over a small issue.'),
(109, N'She finally found her lost keys.'),
(110, N'He finished his homework before dinner.'),
(111, N'The fire destroyed the entire building.'),
(112, N'She has a firm belief in success.'),
(113, N'This dress fits me perfectly.'),
(114, N'He fixed his broken bicycle.'),
(115, N'The road is completely flat.'),
(116, N'Our flight was delayed due to bad weather.'),
(117, N'The floor is made of wood.'),
(118, N'She speaks English fluently.'),
(119, N'Please follow me to the meeting room.'),
(120, N'The vegetables are very fresh.'),
(121, N'She gained a lot of experience in her new job.'),
(122, N'We played a fun game at the party.'),
(123, N'She grows flowers in her garden.'),
(124, N'We gathered information for our project.'),
(125, N'This is a general rule in mathematics.'),
(126, N'She spoke gently to the crying child.'),
(127, N'The elephant is a giant animal.'),
(128, N'He gave me a special gift for my birthday.'),
(129, N'She gave me a book to read.'),
(130, N'I am glad to see you again.'),
(131, N'Climate change is a global issue.'),
(132, N'He wore gloves because it was cold.'),
(133, N'She goes to school every morning.'),
(134, N'His goal is to become a doctor.'),
(135, N'She has golden hair.'),
(136, N'This book is very good.'),
(137, N'The government is making new laws.'),
(138, N'He grabbed his bag and left.'),
(139, N'She dances gracefully on the stage.'),
(140, N'Plants grow faster in sunlight.'),
(141, N'He has a habit of waking up early.'),
(142, N'She looks very happy today.'),
(143, N'He works hard every day.'),
(144, N'Smoking can harm your health.'),
(145, N'He wears a hat to protect from the sun.'),
(146, N'She hates eating spicy food.'),
(147, N'I have a lot of homework to do.'),
(148, N'Good health is very important.'),
(149, N'I can hear music from the next room.'),
(150, N'This box is too heavy to lift.'),
(151, N'Can you help me with this project?'),
(152, N'Please sit here.'),
(153, N'He is a national hero.'),
(154, N'The mountain is very high.'),
(155, N'I love studying history.'),
(156, N'He hit the ball very hard.'),
(157, N'She held my hand tightly.'),
(158, N'I want to go home now.'),
(159, N'I hope you will pass the exam.'),
(160, N'That is a huge mistake.'),
(161, N'She has a great idea for the project.'),
(162, N'This is the ideal place for a vacation.'),
(163, N'He identified the thief from the CCTV footage.'),
(164, N'She ignored his rude comment.'),
(165, N'He is ill and cannot go to school.'),
(166, N'The teacher illustrated the lesson with examples.'),
(167, N'Imagine living in a world without electricity.'),
(168, N'He needs immediate medical attention.'),
(169, N'The company imports goods from China.'),
(170, N'She is trying to improve her English skills.'),
(171, N'The price includes breakfast.'),
(172, N'The company increased salaries last year.'),
(173, N'The tech industry is growing rapidly.'),
(174, N'His parents had a strong influence on his career.'),
(175, N'She informed us about the meeting.'),
(176, N'His initial reaction was surprise.'),
(177, N'He injured his leg while playing football.'),
(178, N'It is very warm inside the house.'),
(179, N'He chose tea instead of coffee.'),
(180, N'This book interests me a lot.'),
(181, N'He bought a new leather jacket.'),
(182, N'I love eating toast with strawberry jam.'),
(183, N'My birthday is in January.'),
(184, N'She is wearing blue jeans.'),
(185, N'He made some fruit jelly for dessert.'),
(186, N'His life is in jeopardy.'),
(187, N'The jet took off on time.'),
(188, N'She loves wearing gold jewelry.'),
(189, N'He completed a 1000-piece jigsaw puzzle.'),
(190, N'The bells jingle beautifully at Christmas.'),
(191, N'He is always in a jolly mood.'),
(192, N'She works as a journalist for a famous newspaper.'),
(193, N'Their journey across the country was exciting.'),
(194, N'The judge announced the verdict.'),
(195, N'The orange was very juicy.'),
(196, N'The dog jumped over the fence.'),
(197, N'The two roads meet at a junction.'),
(198, N'They explored the deep jungle.'),
(199, N'He is a junior engineer in the company.'),
(200, N'They fought for social justice.'),
(201, N'He keeps his room clean.'),
(202, N'I lost my house key.'),
(203, N'She is very kind to everyone.'),
(204, N'The king ruled the country wisely.'),
(205, N'He kicked the ball into the goal.'),
(206, N'She gave him a kiss on the cheek.'),
(207, N'My mother is cooking in the kitchen.'),
(208, N'Be careful with that sharp knife.'),
(209, N'He has a lot of knowledge about history.'),
(210, N'Someone is knocking on the door.'),
(211, N'He injured his knee while running.'),
(212, N'She knows the answer to the question.'),
(213, N'He is known for his kindness.'),
(214, N'He tied a knot in the rope.'),
(215, N'The kid is playing in the park.'),
(216, N'The hunter killed a deer.'),
(217, N'Kangaroos are native to Australia.'),
(218, N'The children are flying a kite.'),
(219, N'The kickoff of the match was at 7 PM.'),
(220, N'The boxer won by a knockout.'),
(221, N'The bottle has a colorful label.'),
(222, N'Hard labor is necessary for success.'),
(223, N'He climbed up the ladder.'),
(224, N'The landscape is breathtaking.'),
(225, N'English is an international language.'),
(226, N'The company has a large customer base.'),
(227, N'They laughed at the joke.'),
(228, N'The company will launch a new product.'),
(229, N'She consulted a lawyer for legal advice.'),
(230, N'He is too lazy to clean his room.'),
(231, N'The leader gave a motivational speech.'),
(232, N'The leaf fell from the tree.'),
(233, N'She learns new things every day.'),
(234, N'The professor gave an interesting lecture.'),
(235, N'It is not legal to park here.'),
(236, N'The length of the river is impressive.'),
(237, N'She wrote a letter to her friend.'),
(238, N'The library is full of books.'),
(239, N'The room is full of light.'),
(240, N'She is lucky to win the lottery.'),
(241, N'The machine is broken.'),
(242, N'She bought a fashion magazine.'),
(243, N'The magician performed magic tricks.'),
(244, N'He maintains a healthy lifestyle.'),
(245, N'Mathematics is his major in college.'),
(246, N'She manages the company efficiently.'),
(247, N'The stock market is unpredictable.'),
(248, N'They got married last year.'),
(249, N'The chair is made of strong material.'),
(250, N'This matter needs urgent attention.'),
(251, N'He measured the length of the table.'),
(252, N'He takes medicine for his headache.'),
(253, N'She is a member of the club.'),
(254, N'My childhood memory is vivid.'),
(255, N'He mentioned your name in the meeting.'),
(256, N'I sent you a message last night.'),
(257, N'The door is made of metal.'),
(258, N'He stood in the middle of the crowd.'),
(259, N'The city has many modern buildings.'),
(260, N'She loves listening to classical music.'),
(261, N'What is your name?'),
(262, N'The nation is developing rapidly.'),
(263, N'She prefers natural beauty.'),
(264, N'It is necessary to drink water daily.'),
(265, N'We need more time to complete the project.'),
(266, N'He always has a negative attitude.'),
(267, N'My neighbor is very friendly.'),
(268, N'The company has a wide network.'),
(269, N'He never lies.'),
(270, N'She reads the newspaper every morning.'),
(271, N'She is a nice person.'),
(272, N'The stars are bright at night.'),
(273, N'He is from a noble family.'),
(274, N'Everything seems normal today.'),
(275, N'They traveled to the north.'),
(276, N'I noticed a mistake in your report.'),
(277, N'He wrote a bestselling novel.'),
(278, N'What is your phone number?'),
(279, N'Good nutrition is important for health.'),
(280, N'The nurse took care of the patients.'),
(281, N'His objective is to improve his skills.'),
(282, N'She obtained a scholarship for her studies.'),
(283, N'It is obvious that he is lying.'),
(284, N'We met on a special occasion.'),
(285, N'The house is occupied by a large family.'),
(286, N'The accident occurred at midnight.'),
(287, N'He offered to help with the work.'),
(288, N'She works in an office.'),
(289, N'The official statement was released yesterday.'),
(290, N'I often go to the gym.'),
(291, N'This house is very old.'),
(292, N'He omitted an important detail in his report.'),
(293, N'He opened the door for her.'),
(294, N'The machine operates smoothly.'),
(295, N'Everyone has a different opinion.'),
(296, N'She got an opportunity to study abroad.'),
(297, N'Their opinions are opposite.'),
(298, N'He ordered a pizza for dinner.'),
(299, N'He is just an ordinary person.'),
(300, N'She organized the meeting very well.'),
(301, N'The package arrived this morning.'),
(302, N'Turn to page ten in your book.'),
(303, N'He felt pain in his knee.'),
(304, N'She painted a beautiful picture.'),
(305, N'He wrote his essay on paper.'),
(306, N'The first paragraph is very important.'),
(307, N'They walked in the park.'),
(308, N'I have a particular interest in history.'),
(309, N'They had a great party last night.'),
(310, N'He passed the exam with high scores.'),
(311, N'The passenger sat by the window.'),
(312, N'This dress has a beautiful pattern.'),
(313, N'They prayed for world peace.'),
(314, N'The weather is perfect today.'),
(315, N'She performed a song on stage.'),
(316, N'The period of study is four years.'),
(317, N'He is a kind person.'),
(318, N'She took a picture of the sunset.'),
(319, N'They planned a trip to the mountains.'),
(320, N'The children played in the garden.'),
(321, N'He has the qualifications for the job.'),
(322, N'The quality of this product is excellent.'),
(323, N'The quantity of sugar is too much.'),
(324, N'A quarter of the cake is left.'),
(325, N'She asked a difficult question.'),
(326, N'We queued for the tickets.'),
(327, N'He gave a quick answer.'),
(328, N'The library is very quiet.'),
(329, N'She is quite tall.'),
(330, N'He quoted a famous author.'),
(331, N'They had a quarrel last night.'),
(332, N'The village has a quaint charm.'),
(333, N'Water quenches thirst.'),
(334, N'They are on a quest for knowledge.'),
(335, N'The horse got stuck in quicksand.'),
(336, N'Her lips quivered with emotion.'),
(337, N'The quotient of ten divided by two is five.'),
(338, N'The patients were placed in quarantine.'),
(339, N'The point lies in the first quadrant.'),
(340, N'Scientists study quasars to understand the universe.'),
(341, N'He won the race easily.'),
(342, N'It rained heavily last night.'),
(343, N'She raised her hand to ask a question.'),
(344, N'He chose a random number.'),
(345, N'The price range is between ten and twenty dollars.'),
(346, N'The company experienced rapid growth.'),
(347, N'It is rare to see snow in this area.'),
(348, N'She reacted quickly to the news.'),
(349, N'He realized his mistake too late.'),
(350, N'There is no reason to be upset.'),
(351, N'She received a gift from her friend.'),
(352, N'I read a recent article about climate change.'),
(353, N'I did not recognize her at first.'),
(354, N'He recommended a good book to me.'),
(355, N'We need to reduce pollution.'),
(356, N'She refused to answer the question.'),
(357, N'He is a regular customer.'),
(358, N'They have a good relation with each other.'),
(359, N'I felt a sense of relief after the exam.'),
(360, N'This job requires a lot of experience.'),
(361, N'This place is safe for children.'),
(362, N'The meal satisfied our hunger.'),
(363, N'She saved money for her trip.'),
(364, N'The project is on a large scale.'),
(365, N'The movie has an amazing scene.'),
(366, N'My schedule is very busy.'),
(367, N'He loves studying science.'),
(368, N'He searched for his lost phone.'),
(369, N'She told me a big secret.'),
(370, N'This book has ten sections.'),
(371, N'He secured the door before leaving.'),
(372, N'She selected a red dress.'),
(373, N'She has a good sense of humor.'),
(374, N'They decided to separate after many years.'),
(375, N'This is a serious matter.'),
(376, N'The hotel provides excellent service.'),
(377, N'His shadow was visible on the wall.'),
(378, N'The knife is very sharp.'),
(379, N'The homeless man found a shelter.'),
(380, N'The sun shines brightly in the morning.'),
(381, N'He put his books on the table.'),
(382, N'She has a great talent for singing.'),
(383, N'They talked for hours.'),
(384, N'His target is to finish the project on time.'),
(385, N'The soup tastes delicious.'),
(386, N'She teaches English at a school.'),
(387, N'Our team won the championship.'),
(388, N'Technology is improving every day.'),
(389, N'The temperature is very high today.'),
(390, N'She has a tender heart.'),
(391, N'The term "AI" stands for artificial intelligence.'),
(392, N'He passed the math test.'),
(393, N'The theory of relativity is famous.'),
(394, N'The book is very thick.'),
(395, N'He threw the ball to his friend.'),
(396, N'I bought a ticket for the concert.'),
(397, N'She keeps her room tidy.'),
(398, N'The boy was too timid to speak.'),
(399, N'He loves to travel around the world.'),
(400, N'She treasures her childhood memories.'),
(401, N'The building looks very ugly.'),
(402, N'His ultimate goal is to become a doctor.'),
(403, N'She forgot her umbrella at home.'),
(404, N'His story was unbelievable.'),
(405, N'I am uncertain about my decision.'),
(406, N'The chair is very uncomfortable.'),
(407, N'She looks unhappy today.'),
(408, N'All students must wear a uniform.'),
(409, N'This design is very unique.'),
(410, N'The length is measured in units.'),
(411, N'Music is a universal language.'),
(412, N'His identity remains unknown.'),
(413, N'Unlike his brother, he is very quiet.'),
(414, N'They unloaded the truck quickly.'),
(415, N'The weather is very unpleasant today.'),
(416, N'He updated his profile picture.'),
(417, N'They upgraded the system last week.'),
(418, N'This is an urgent matter.'),
(419, N'She uses a laptop for work.'),
(420, N'The apartment has all the utilities included.'),
(421, N'The room is vacant now.'),
(422, N'We are planning a vacation to Hawaii.'),
(423, N'The village is located in a valley.'),
(424, N'This ring is very valuable.'),
(425, N'The delivery van arrived late.'),
(426, N'The ocean is vast and mysterious.'),
(427, N'Eating vegetables is good for health.'),
(428, N'They bought a new vehicle last week.'),
(429, N'The document needs to be verified.'),
(430, N'The team celebrated their victory.'),
(431, N'The view from the top is amazing.'),
(432, N'He grew up in a small village.'),
(433, N'The movie was too violent for children.'),
(434, N'He attended a virtual meeting.'),
(435, N'The stars are visible at night.'),
(436, N'We visited our grandparents last weekend.'),
(437, N'She has strong vocal skills.'),
(438, N'She volunteers at the hospital.'),
(439, N'Everyone has the right to vote.'),
(440, N'The letter "a" is a vowel.'),
(441, N'Please wait for me outside.'),
(442, N'I wake up at six o’clock every day.'),
(443, N'She walks to school every morning.'),
(444, N'There is a picture on the wall.'),
(445, N'I want to buy a new phone.'),
(446, N'The weather is warm today.'),
(447, N'She washed the dishes after dinner.'),
(448, N'He watched a movie last night.'),
(449, N'She drinks a lot of water every day.'),
(450, N'The waves are very high today.'),
(451, N'He felt weak after the long journey.'),
(452, N'The weather is very nice today.'),
(453, N'She created a new web page.'),
(454, N'They welcomed the guests warmly.'),
(455, N'The sun sets in the west.'),
(456, N'The car has four wheels.'),
(457, N'She whispered something in his ear.'),
(458, N'He wore a white shirt.'),
(459, N'The forest is full of wild animals.'),
(460, N'She opened the window to get fresh air.'),
(461, N'The doctor took an X-ray of my leg.'),
(462, N'Xenophobia is a serious social issue.'),
(463, N'Please Xerox these documents.'),
(464, N'The child played the xylophone happily.'),
(465, N'Xenon is used in some types of lamps.'),
(466, N'The graph is measured along the X-axis.'),
(467, N'He is a xenophile who loves traveling.'),
(468, N'Xylography was used in ancient printing.'),
(469, N'Xenogenesis refers to offspring different from parents.'),
(470, N'The xiphoid process is part of the sternum.'),
(471, N'The xenolithic rock was studied by geologists.'),
(472, N'The doctor used a xenoplastic tissue for treatment.'),
(473, N'Xylotomy is used in botany studies.'),
(474, N'Xenotransplant technology is advancing rapidly.'),
(475, N'The patient received a xenograft for treatment.'),
(476, N'Xylose is used in some artificial sweeteners.'),
(477, N'Xenocracy happened in colonial times.'),
(478, N'Xenotropic viruses infect different species.'),
(479, N'Xenogamy occurs in some plant species.'),
(480, N'The Xenarthra family includes armadillos.'),
(481, N'They bought a luxurious yacht.'),
(482, N'The children are playing in the yard.'),
(483, N'She yawned because she was sleepy.'),
(484, N'This year has been very challenging.'),
(485, N'She wore a yellow dress.'),
(486, N'Yes, I will help you.'),
(487, N'We met yesterday at the park.'),
(488, N'He has not finished his work yet.'),
(489, N'The farm yields a good harvest.'),
(490, N'He is a young athlete.'),
(491, N'Youth is the time to explore new things.'),
(492, N'She eats yogurt for breakfast.'),
(493, N'The yolk of the egg is yellow.'),
(494, N'He yelled loudly for help.'),
(495, N'The company holds a yearly meeting.'),
(496, N'The crowd shouted a loud yahoo.'),
(497, N'The food is so yummy!'),
(498, N'She practices yoga every morning.'),
(499, N'Look at that house over yonder.'),
(500, N'He is a typical yuppie in the city.'),
(501, N'The zebra has black and white stripes.'),
(502, N'The temperature dropped to zero.'),
(503, N'Zinc is an important mineral for health.'),
(504, N'This area is a restricted zone.'),
(505, N'We visited the zoo last Sunday.'),
(506, N'He zoomed in to see the details.'),
(507, N'A soft zephyr blew through the trees.'),
(508, N'He reached the zenith of his career.'),
(509, N'Her zodiac sign is Leo.'),
(510, N'The zipper on my jacket is broken.');








-- Truy vấn tìm kiếm từ điển với phiên âm
DECLARE @searchWord NVARCHAR(100) = 'Absorb';  -- Thay 'apple' bằng từ cần tìm

SELECT 
    W.word AS 'Từ',
    (SELECT STRING_AGG(P.phonetic, ', ') FROM Phonetic P WHERE P.word_id = W.word_id) AS 'Phiên âm',
    (SELECT STRING_AGG(WT.word_type, ', ') FROM WordTypes WT WHERE WT.word_id = W.word_id) AS 'Loại từ',
    (SELECT STRING_AGG(M.definition, '; ') FROM Meanings M WHERE M.word_id = W.word_id) AS 'Nghĩa',
    (SELECT STRING_AGG(E.example, ' | ') FROM Examples E WHERE E.word_id = W.word_id) AS 'Ví dụ'
FROM Words W
WHERE W.word = @searchWord;




